apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: prometheus-grafana
          servicePort: 80
        path: /grafana
  - http:
      paths:
      - backend:
          serviceName: prometheus-kube-prometheus-prometheus
          servicePort: 9090
        path: /prometheus