apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  routePrefix: /prometheus
  rules:
  - http:
      paths:
      - backend:
          serviceName: prometheus-server
          servicePort: 80
        path: /prometheus